// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateStatistics(arg1:string):Promise<Record<string, any>>;

export function OpenFileDialog():Promise<string>;

export function OpenText(arg1:string):Promise<string>;

export function SaveAs(arg1:string):Promise<string>;

export function SaveCurrentFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileDialog():Promise<string>;

export function SaveText(arg1:string,arg2:string):Promise<void>;
