// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateStatistics(arg1) {
  return window['go']['main']['App']['CalculateStatistics'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenText(arg1) {
  return window['go']['main']['App']['OpenText'](arg1);
}

export function SaveAs(arg1) {
  return window['go']['main']['App']['SaveAs'](arg1);
}

export function SaveCurrentFile(arg1, arg2) {
  return window['go']['main']['App']['SaveCurrentFile'](arg1, arg2);
}

export function SaveFileDialog() {
  return window['go']['main']['App']['SaveFileDialog']();
}

export function SaveText(arg1, arg2) {
  return window['go']['main']['App']['SaveText'](arg1, arg2);
}
